test03/photo/urls.py
from django.urls import path
from django.views.generic.detail import DetailView

from .views import *
from .models import Photo

app_name = 'photo'  # 네임스페이스로 사용되는 값이다.
# 템플릿에서 url 템플릿 태그를 사용할 때 app_name 값이 설정되어 있다면
# [app_name:URL패턴이름] 형태로 사용한다.
urlpatterns = [
    path('', photo_list, name='photo_list'),  # 함수형(def) 뷰
    path('detail/<int:pk>/', DetailView.as_view(model=Photo,
                                                template_name='photo/detail.html'), name='photo_detail'),
    # 제네릭 뷰를 그대로 사용하는 인라인 뷰
    # urls.py 에서 인라인 코드로 작성할 수 있습니다. path 함수에 인수로 전달할 때는
    # as_view안에 클래스 변수들을 설정해 사용합니다.
    path('upload/', PhotoUploadView.as_view(), name='photo_upload'),
    path('delete/<int:pk>/', PhotoDeleteView.as_view(), name='photo_delete'),
    path('update/<int:pk>/', PhotoUpdateView.as_view(), name='photo_update'),
    # 함수 형 뷰는 뷰 이름만 써주고 클래스(class) 형 뷰는 뒤에 .as_view()를 붙인다.
]

test03/test03/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('photo.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

test03/photo/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User  # 가져온 User를 class Photo 에서 사용


class Photo(models.Model):
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='user_photos')
    # ForeignKey를 사용하여 User 테이블과 관계를 만듭니다. 여기서 User 모델은 장고에서 기본적으로 사용하는
    # 사용자 모델입니다. on_delete 인수는 연결된 모델이 삭제될 경우 현재 모델의 값은 어떻게 할 것이냐 이다.
    '''
    CASCADE : 연결된 객체가 지워지면 해당 하위 객체도 같이 삭제
    PROTECT : 하위 객체가 남아 있다면 연결된 객체가 지워지지 않음
    SET_NULL : 연결된 객체만 삭제하고 필드 값을 NULL로 설정
    SET_DEFAULT : 연결된 객체만 삭제하고 필드 값을 설정된 기본 값으로 변경
    SET() : 연결된 객체만 삭제하고 지정한 값으로 변경
    DO_NOTHING : 아무 일도 하지 않음
    '''
    # 세 번째 인수인 related_name 은 연결된 객체에서 하위 객체의 목록을 부를 때 사용할 이름이다.
    # Photo 모델을 예로 들면 어떤 유저가 작성한 글을 불러 올 때는 유저 객체에 user_photos 속성을 참조하면 된다.
    photo = models.ImageField(upload_to=r'./photos',
                              default=r'photos/no_image.png')
    # upload_to 는 사진이 업로드 될 경로를 설정한다. 만약 업로드가 되지 않을 경우 default 값으로 대체.
    text = models.TextField()
    # 텍스트 필드, 문자열 길이 제한 X
    created = models.DateTimeField(auto_now_add=True)
    # 글 작성 일을 저장하기 위한 날짜시간 필드
    # auto_now_add 옵션을 설정하면 객체가 추가될 때 자동으로 값을 설정한다.
    # 한마디로 게시글이 작성될 때의 시간을 갖고 upload_to 의 경로에 맞게끔 값을 넣어준다.
    updated = models.DateTimeField(auto_now=True)
    # 글 수정 일을 저장하기 위한 날짜시간 필드이다. auto_now 옵션을 설정하면 객체가 수정 될 때 마다 자동으로 값을 설정한다.

    class Meta:  # 옵션 클래스
        ordering = ['-updated']
    # ordering 클래스 변수는 해당 모델의 객체들을 어떤 기준으로 정렬할 것인지 설정하는 옵션
    # -updated 로 설정했으니 글 수정 시간의 내림차순으로 정렬할것이다.

    def __str__(self):
        return self.author.username + " " + self.created.strftime("%Y-%m-%d %H:%M:%S")
    # 작성자의 이름과(author.username) 글 작성일을 합친 문자열을 반환한다.

    def get_absolute_url(self):
        return reverse('photo:photo_detail', args=[str(self.id)])  # photo/id
    # 객체의 상세 페이지의 주소를 반환하는 메서드입니다.
    # 객체를 수정했을 때 이동할 주소를 위해 호출되기도 하고 템플릿에서 상세 화면으로 이동하는
    # 링크를 만들 때 호출하기도 합니다. 이런 주소를 만들기 위해서는 reverse 메서드를 사용하는데
    # reverse 메서드는 URL 패턴 이름을 가지고 해당 패턴을 찾아 주소를 만들어주는 함수이다.

test03/photo/views.py
from django.shortcuts import render
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.shortcuts import redirect

from .models import Photo


class PhotoUploadView(CreateView):  # CreateView 를 PhotoUploadView가 상속받는다.
    model = Photo
    fields = ['photo', 'text']
    template_name = 'photo/upload.html'  # 클래스 변수 생성, 이 변수는 실제 사용할 템플릿을 설정한다.

    def form_valid(self, form):  # 업로드를 끝내고 이동할 페이지를 호출하기 위해 사용하는 메서드
        # 이 메서드를 오버라이드해서 작성자를 설정하는 기능을 추가했다.
        # 작성자는 현재 로그인한 사용자로 설정한다.
        form.instance.author_id = self.request.user.id
        if form.is_valid():  # is_vaild() 입력 된 값들을 검증한다.
            form.instance.save()  # 이상이 없다면 데이터베이스에 저장하고
            return redirect('/')  # redirect 메서드를 이용해 메인 페이지로 이동한다.
        else:
            # 문제가 있다면 내용을 그대로 작성 페이지에 표시한다.
            return self.render_to_response({'form': form})


def photo_list(request):
    photos = Photo.objects.all()  # 데이터베이스에 저장 된 모든 사진을 불러온다.
    for a in photos.values_list():
        print(a)
    return render(request, 'photo/list.html', {'photos': photos})
# 템플릿과 뷰를 연동하기 위해서 render 함수를 사용한다.
# render 함수는 첫 번째 인자로 request
# 두 번째 인자는 랜더링 할 템플릿
# 세 번째 인자는 템플릿에 보내줄 객체나 값


class PhotoDeleteView(DeleteView):  # 제네릭 뷰 DeleteView를 사용하기 위해 상속 받는다.
    model = Photo
    success_url = '/'  # 성공 시 사이트 메인으로 이동한다.
    template_name = 'photo/delete.html'


class PhotoUpdateView(UpdateView):  # 제네릭 뷰 UpdateView를 사용하기 위해 상속 받는다.
    model = Photo
    fields = ['photo', 'text']
    template_name = 'photo/update.html'

test03/photo/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
        integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
        integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
        integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
        crossorigin="anonymous"></script>
    <title>Mammography Detection {% block title %}{% endblock %}</title>
</head>

<body>

    <div class="container">
        <header class="header clearfix">
            <nav class="navbar navbar-expand-lg navbar-light bg-light">
                <a class="navbar-brand" href="/">Mammography Detection</a>
                <ul class="nav">
                    <li class="nav-item"><a href="/" class="active nav-link ">Home</a></li>
                    {% if user.is_authenticated %}
                    <!-- 로그인 여부를 판단할 수 있다.-->
                    <li class="nav-item"><a href="#" class="nav-link">Welcome, {{user.get_username}}</a></li>
                    <li class="nav-item"><a href="{% url 'photo:photo_upload' %}" class="nav-link">Upload</a></li>
                    <li class="nav-item"><a href="#" class="nav-link">Logout</a></li>
                    {% else %}
                    <li class="nav-item"><a href="#" class="nav-link">Login</a></li>
                    <li class="nav-item"><a href="#" class="nav-link">Signup</a></li>
                    {% endif %}
                </ul>
            </nav>
        </header>
        {% block content %}
        {% endblock %}

        <footer class="footer">
            <p>&copy; Hyun </p>
        </footer>
    </div>


</body>

</html>

test03/photo/templates/photo/delete.html
{% extends 'base.html' %}
{% block title %}- Delete{% endblock %}

{% block content %}
<div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-8 panel panel-default">
        <div class="alert alert-info">
            Do you want to delete {{object}}? <!-- 2044smile 2019-07-18 04:40:03 -->
        </div>
        <form action="" method="post">
            {{form.as_p}}
            {% csrf_token %}
            <input type="submit" class="btn btn-danger" value="Confirm">
        </form>
    </div>
    <div class="col-md-2"></div>
</div>
{% endblock %}

test03/photo/templates/photo/detail.html
{% extends 'base.html' %}
{% block title %}
    {{object.text|truncatechars:10}} <!-- 문자열을 지정 글자갯수까지 줄이며, 줄여질 경우 끝 에 "..."를 추가 -->
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8 panel panel-default">
            <p><img src="{{object.photo.url}}" style="width:100%;"></p>
            <button type="button" class="btn btn-outline-primary btn-sm">
                {{object.author.username}} <!-- 2044smile -->
            </button>
            <p>{{object.text|linebreaksbr}}</p>
            <!-- HTML은 기본적으로 공백문자를 인식하지 못하는데 linebreaksbr 필터를 사용하면 줄바꿈이 일어나는 곳에 <br> 태그를 추가! -->
            <a href="{% url 'photo:photo_delete' pk=object.id %}" class="btn btn-outline-danger btn-sm float-right">
                Delete
            </a>
            <a href="{% url 'photo:photo_update' pk=object.id %}" class="btn btn-outline-danger btn-sm float-right">
                Update
            </a>
        </div>
        <div class="col-md-2"></div>
    </div>
{% endblock%}

test03/photo/templates/photo/list.html
<!--photo/templates/photo/list.html-->
{% extends 'base.html' %}

{% block title %}- List{% endblock %}

{% block content %}
{% for post in photos %}
<div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-8 panel panel-default">
        <!-- 이부분때문에 깨진 화면 출력 -->
        <p><img src="{{post.photo.url}}" style="width:50%;" alt="Image Error"></p>
        <!--<p><img src="../../../media/photos/2020/06/23/Calc-Test_P_00038_RIGHT_CC_1_mask.png" style="width:50%;" alt="Image Error"></p> -->
        <p>{{post.photo.url}}</p>
        <button type="button" class="btn btn-xs btn-info">
            {{post.author.username}}
        </button>
        <p>{{post.text|linebreaksbr}}</p>
        <p class="text-right">
            <a href="{% url 'photo:photo_detail' pk=post.id %}" class="btn btn-xs btn-success">댓글달기</a>
        </p>
    </div>
    <div class="col-md-2"></div>
</div>
{% endfor %}
{% endblock %}

test03/photo/templates/photo/update.html
{% extends 'base.html' %}
{% block title %}
- Update
{% endblock%}

{% block content %}
<div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-8 panel panel-default">
        <form action="" method="post" enctype="multipart/form-data">
            {{form.as_p}}
            {% csrf_token %}
            <input type="submit" class="btn btn-primary" value="Update">
        </form>
    </div>
    <div class="col-md-2"></div>
</div>
{% endblock %}

test03/photo/templates/photo/upload.html
{% extends 'base.html' %}
{% block title %}- Upload{% endblock %}

{% block content%}
<div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-8 panel panel-default">
        <form action="" method="post" enctype="multipart/form-data"> <!-- 업로드 뷰는 form 태그로 구성 -->
            <!-- enctype은 form 태그로 작성한 정보를 어떤 형태로 인코딩해서 서버로 전달할 것인지 결정하는 옵션입니다.
            method 가 "post" 일 때만 사용할 수 있습니다.

            1. application/x-www-form-urlencoded : 기본 옵션입니다. 모든 문자열을 인코딩해 전달하며
            특수 문자는 ASCII HEX 값으로 변환하고 띄어쓰기는 +로 변환하여 전달합니다.
            2. multipart/form-data : 파일 업로드 때 사용하는 옵션이며 데이터를 문자열로 인코딩 하지 않고 전달
            3. text/plain : 띄어쓰기만 +로 변환하고 특별한 인코딩 없이 전달한다.-->
            {{form.as_p}} <!-- 입력form HTML 생성 -->
            {% csrf_token %}
            <input type="submit" class="btn btn-primary" value="Updata">
        </form>
    </div>
    <div class="col-md-2"></div>
</div>
{% endblock %}